# Generated by Django 4.1.2 on 2022-11-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
    ]
