# Generated by Django 4.1.2 on 2023-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hujjatlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка на файл')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('department', models.ManyToManyField(to='Hujjatlar.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
    ]
